In [ ]:
# Data science
# Lab session 1 - Basiscs of statistical analysis

In [1]:
mystring = "Welcome to the session"
print(mystring)

Welcome to the session


In [2]:
myint = 25

In [3]:
whos

Variable   Type    Data/Info
----------------------------
myint      int     25
mystring   str     Welcome to the session


In [4]:
print("The value is ", myint)

The value is  25


In [2]:
import numpy as np

In [4]:
HP_Var = np.loadtxt("HP.csv", dtype=int)
print(HP_Var)

[110 110  93  96  90 110 110 110]


In [6]:
# calculating the mean of HP
# The mean is the average of a set of numbers.
mean_of_HP = np.mean(HP_Var)
print(mean_of_HP)

103.625


In [ ]:
# Question 1
# calculating the median of HP
# The median is the middle value in a set of numbers when they are arranged in order.
median_of_HP = np.median(HP_Var)
print(median_of_HP)

110.0


In [18]:
# Question 2
# calculate the median of mpg file
mp_var = np.loadtxt("MpG.csv", dtype=float)
print(mp_var)

mean_of_mpg = np.mean(mp_var)
print("mean of mpg is ", mean_of_mpg)

median_of_mp = np.median(mp_var)
print(median_of_mp)

[21.  21.  22.8 21.3 23.  23.  23.  23. ]
mean of mpg is  22.2625
22.9


In [ ]:
# importing SciPy library
from scipy import stats

# The mode is the value that appears most frequently in a dataset.

mode_of_hp = stats.mode(HP_Var)
print(mode_of_hp)

ModeResult(mode=np.int64(110), count=np.int64(5))


In [23]:
# Question 3
# calculate the mode of ctype
ctype_var = np.loadtxt("CType.csv", dtype=int)
print(ctype_var)

mode_of_ctype = stats.mode(ctype_var)
print(mode_of_ctype)

# calculate the variance of HP
# Variance measures how spread out your data is
# it tells you how far the numbers are from teh mean on average
# variance is small - if all numbers are close to the mean
# variance is large - if numbers are far from the mean
variance_of_hp = np.var(HP_Var)
print(HP_Var)
print(variance_of_hp)

[6 6 4 6 4 6 4 6]
ModeResult(mode=np.int64(6), count=np.int64(5))
[110 110  93  96  90 110 110 110]
69.984375


In [24]:
# Question 4
# calculate the variance of mpg

variance_of_mpg = np.var(mp_var)
print("variance of mpg: ", variance_of_mpg)

variance of mpg:  0.8223437499999999


In [ ]:
# calculating the standard deviation of HP
# Standard deviation = average distance from the mean (in normal units).

# Standard deviation tells you how much the data typically differs from the mean.
# It is simply the square root of variance.
s_deviation_of_hp = np.std(HP_Var)
print(s_deviation_of_hp)

8.365666440876064


In [27]:
# Question 5
# calcualate the standard deviation of mpg
s_deviation_of_mpg = np.std(mp_var)
print(mp_var)
print(s_deviation_of_mpg)

[21.  21.  22.8 21.3 23.  23.  23.  23. ]
0.9068317098558034


In [31]:
# calculating the range of quantity
# Range is the difference between the largest and smallest values in a dataset.
# range = max value - min value

# method 1 using max and min function
print("the data itself:\n", HP_Var)
largest = max(HP_Var)
print("maximum = ", largest)
smallest = min(HP_Var)
print("minimum = ", smallest)
range = largest - smallest
print("Range= ", range)


# method 2 using for loop
def range(x):
    max = 0
    min = 999999999
    
    for value in x:
        if value > max:
            max = value
        if value < min:
            min = value
    range = max - min
    return range
range_value = range(HP_Var)
print(range_value)

the data itself:
 [110 110  93  96  90 110 110 110]
maximum =  110
minimum =  90
Range=  20
20


In [35]:
# question 6
# calculate range of mpg using both methods

# method 1
print(mp_var)
largest = max(mp_var)
smallest = min(mp_var)
range_value = largest - smallest
print("range of mpg: ", range_value)

def find_range(data):
    max_val = data[0]
    min_val = data[0]

    for value in data:
        if value > max_val:
            max_val = value
        if value < min_val:
            min_val = value
    
    return max_val - min_val

print("range using for loop: ", find_range(mp_var))

[21.  21.  22.8 21.3 23.  23.  23.  23. ]
range of mpg:  2.0
range using for loop:  2.0
