In [ ]:
# Data science
# lab session 2 - probability and linear algebra for data science

In [2]:
import numpy as np
from scipy import stats
import math as mt
import random as rnd

In [ ]:
# matrix operations

# np.array() converts Python data (lists or tuples) into a NumPy array object.
# NumPy performs element-wise addition.
# It adds each element in the same position.

# `np.array()` → creates a mathematical matrix  
# `+` and `-` → element-wise operations  
# `np.dot()` → true matrix multiplication 

x = np.array( ((2, 3), (3, 5) ))
# [ 2   3 ]
# [ 3   5 ]
y = np.array( ((1, 2), (5, -1)))
# [ 1   2 ]
# [ 5  -1 ]

# Each one is a 2×2 matrix.
# What is a MATRIX MULTIPLICATION
# You multiply a row from the first matrix
# with a column from the second matrix
# and add the results.


addition = x + y
print("x:", x)
print("y:", y)
print("addition of x and y is", addition)

subtraction = x - y
print("difference between x and y", subtraction)

# [ 2   3 ]
# [ 3   5 ]

# [ 1   2 ]
# [ 5  -1 ]

# Row 1 of x → [2, 3]
# Column 1 of y → [1, 5]

# Now multiply matching positions:

# (2 × 1) + (3 × 5) = 17 - the first value in the result matrix [17  ?] [?   ?]
# (2 * 2) + (3 * -1) = 1 - the next value [17   1] [?  ?]

# Row 2 of x → [3, 5]
# Column 1 of y → [1, 5]
# (3 * 1) + (5 * 5) = 28 - [17  1] [28  ?]
# (3 * 2) + (5 * -1) = 1 => [17 1] [28 1]

# Matrix multiplication means:
# Take a row from X
# Take a column from Y
# Multiply matching elements
# Add them
# That gives one output value
# Repeat for all columns of Y
# Then move to next row of X
dot_product = np.dot(x, y)
print("dot product of x and y", dot_product)

x: [[2 3]
 [3 5]]
y: [[ 1  2]
 [ 5 -1]]
addition of x and y is [[3 5]
 [8 4]]
difference between x and y [[ 1  1]
 [-2  6]]
dot product of x and y [[17  1]
 [28  1]]


In [8]:
# matrix() function of numpy
# for np.matrix objects
# '*' means matrix multiplication, in here: x * y is equivalent to np.dot(x, y)
# BUT for np.array, x * y is element wise multiplication
x = np.matrix( ((2, 3), (3, 5)))
y = np.matrix( ((1, 2), (5, -1)))
print(x)
print(y)

multiplication = x*y
print("multiplicaiton of x and y:\n", multiplication)

# best practice do not use np.matrix(), use array and x @ y; @ is clean matrix multiplication operator

x = np.array(((2, 3), (3, 5)))
y = np.array(((1, 2), (5, -1)))
print("the modern way using @ operator for matrix multiplication:\n", x @ y)

[[2 3]
 [3 5]]
[[ 1  2]
 [ 5 -1]]
multiplicaiton of x and y:
 [[17  1]
 [28  1]]
the modern way using @ operator for matrix multiplication:
 [[17  1]
 [28  1]]


In [18]:
# Question 1
# You are given with metrices "a" contains ((45,35), (21,51)) , "b" contains ((1,2), (3,4)) and, 
# "c" contains ((100,101), (200,201)). Now perform the following operations given:

# ***Hint:*** You can either use "array" or "matrix" function.

# 1. a+b
# 2. b-c
# 3. a*c
# 4. b.c

a = np.array(((45,35), (21,51)))
b = np.array(((1,2), (3,4)))
c = np.array(((100,101), (200,201)))

print("a\n", a)
print("b\n", b)
print("c\n", c)

# 1. addition
print("addition of a b\n", a + b)

# 2. subtraction
print("subtraction of b c\n", b - c)

# 3. element wise multiplication
print("element wise multiplication of a and c\n", a * c)

# 4. b.c or b @ c
print("matrix multiplication using dot of b and c\n", np.dot(b, c))
print("matrix multiplication using @ operator between b and c\n", b @ c)


a
 [[45 35]
 [21 51]]
b
 [[1 2]
 [3 4]]
c
 [[100 101]
 [200 201]]
addition of a b
 [[46 37]
 [24 55]]
subtraction of b c
 [[ -99  -99]
 [-197 -197]]
element wise multiplication of a and c
 [[ 4500  3535]
 [ 4200 10251]]
matrix multiplication using dot of b and c
 [[ 500  503]
 [1100 1107]]
matrix multiplication using @ operator between b and c
 [[ 500  503]
 [1100 1107]]


In [ ]:
# Vector operations

x = np.array([1, 2, 5])
y = np.array([5, -1, 6])
print(x)
print(y)
addition = x + y
print("addition of x anpd y", addition)

print("differnece between x and y\n", x - y)
# dot product in vectors:
# multiply matching position and add the results

# x = [a, b, c]
# y = [d, e, f]
# dot = (a×d) + (b×e) + (c×f)

# x * y in arrays = element-wise multiplication, the result will still be a vector
print("dot product of x and y\n", np.dot(x, y))

[1 2 5]
[ 5 -1  6]
addition of x anpd y [ 6  1 11]
differnece between x and y
 [-4  3 -1]
dot product of x and y
 33


In [ ]:
# Vector modulus
x = np.array([1, 2, 3, 4, 5])

modulus = np.sqrt(np.dot(x, x)) # dot(v, v), dot product of the x with itself; and returns square root of the product
print(np.sqrt(55))
print(modulus)

7.416198487095663
7.416198487095663


In [30]:
# multiplication of vector with a scalar value; multiply() function
# scalar means multiply every element in the vector by that number
vector = np.array([1, 2, 3])
n = 100
print(np.multiply(vector, n))
print(vector * n)

[100 200 300]
[100 200 300]


In [33]:
# Question 2
# You are given with a vector/1D matrix, ([90,200,20,1,54,200]) contains the club card points 
# he earned on different occassions. You are giving him 2 times more points and 
# you want to store that 2 times rewarded points in a new vector/1D array. 
# Write a code to store this infomation. 

my_vector = np.array([90,200,20,1,54,200])
print(my_vector)
new_vector = my_vector * 2
print("doubled points in the card:", new_vector)

[ 90 200  20   1  54 200]
doubled points in the card: [180 400  40   2 108 400]


In [ ]:
# Generating Binominal Distribution
"""
binominal distribution
it models the number of successes in a fixed number of independent trials.
it is used when: 
- you repeat an experiment n times; 
- each trial has only two outcomes (success or failure)
- the probability success p stays the same
ex: tossing a coin 10 times and counting how many heads apper
"""
# n - number of trials
# p - probability of success in each trial
X = stats.binom(10, 0.2) # n = 10; p = 0.2 - 20% chance of success each time
# X - REPRESENTS THE NUMBER OF SUCCESSES IN n TRIALS, WHERE EACH TRIAL HAS PROBABILITY p OF SUCCESS.
"""
PMF (probability mass function) - the probability of getting exactly k successes
CDF (cumulative distribution function) - the probability of getting k or fewer successes
Mean = n * p; the mean is the average value you expect if you repeat the experiment many times
Variance = n*p*(1-p) - it tells how spread out the results are from the mean,
    it measures how much the outcomes fluctute;
    if variance is small - results stay close to the mean
    if variance is large - results are more spread out
Standard deviation (std) - std = sqrt(variance)
    it measures spread like variance, but it is in the same units as the data and it is easier to understand

mean = 2 -> average number of successes is 2
std = 1.26 -> most results are roughly withing 1.26 of 2; so most outcomes will be 2 +- 1.26
"""
print(X.rvs()) # number of successes in n time trial where success chance is 20%
print(X.pmf(3)) # P(X=3)probability of getting exactly 3 successes out of 10
print(X.cdf(4)) # P(X <= 4) probability of getting at most 4 successes
print(X.mean())
print(X.var())
print(X.std())

3
0.20132659199999992
0.9672065024
2.0
1.5999999999999999
1.2649110640673518


In [ ]:
# Question 3
# You are given a dice which you can roll five times to check how many times you find "6" 
# and probability of the roll being a success is 80%.  
# Write a code to find the probability mass function (pmf) 
# and cumulative distribution function (cdf) for the final trial.

X = stats.binom(5, 0.8) # = totoal number of successes in 5 rolls
pmf = X.pmf(5) # what is the probability that all 5 rolls are success;/ probability of 5 successes 
print(pmf)

print(X.cdf(5))
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

0.3276800000000002
1.0


In [ ]:
# Generating normal distribution
# Mean → center of curve
# Variance → spread
# Standard deviation → square root of variance
# PDF → height of curve
# CDF → actual probability up to a point
A = stats.norm(3, mt.sqrt(16)) # mean = 3, standard deviation = 4, where variance is 16
print(A.pdf(4))
print(A.cdf(2))

0.09666702920071232
0.4012936743170763


In [ ]:
# Question 4
# Write a code to calculate the probability density function and 
# cumulative distrbution function for a normal distribution 
# with $μ=9 ,σ^2=64$, for probability density equals 6

A = stats.norm(9, mt.sqrt(64))
print("pdf:", A.pdf(6))
print("cdf:", A.cdf(6))
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


pdf: 0.04648188673372112
cdf: 0.3538302333272762


In [104]:
# Question 5
# Write a code to calculate the normal probability density function for value "11" 
# in the range, given, mean=10 and standard deviation=2.
# **Hint:** remember to use standard deviation instead of variance in the code.
A = stats.norm(10, 2)
print(A.pdf(11))


0.17603266338214976
