In [ ]:
# lab session 4
# understanding numpy array and pandas

In [1]:
import numpy as np

In [4]:
my_1d_array = np.array([1, 2, 4, 9, 16, 25])
print("the array:", my_1d_array)
print(type(my_1d_array))
print(my_1d_array.dtype)
print(my_1d_array.ndim)
print(my_1d_array.shape)

the array: [ 1  2  4  9 16 25]
<class 'numpy.ndarray'>
int64
1
(6,)


In [9]:
# Quesiton 1
the_array = np.array([2.2, 50.5,3.44, 9.6, 7.5, 21.2])
print(the_array)
print("type of elements:", the_array.dtype)
print("type of the array:", type(the_array))
print("shape of the array:", the_array.shape)
print("the array itself:", the_array)

[ 2.2  50.5   3.44  9.6   7.5  21.2 ]
type of elements: float64
type of the array: <class 'numpy.ndarray'>
shape of the array: (6,)
the array itself: [ 2.2  50.5   3.44  9.6   7.5  21.2 ]


In [24]:
# useful functions to create numpy arrays
a = np.linspace(0, 1, 11) # 11 elements, uniformly spaced, 0 to 1
print(a, a.shape)

b = np.arange(0, 20, 2.5) # 0 to 20 elements spaced by 2.5
print(b, b.shape)

c = np.zeros(5) # 1d array consisting of 5 zeros
print(c.shape)
print(c)

M = np.zeros((2, 5)) # 2x5 (2 rows, 5 columns) array of zeros
print(M.shape)
print(M)

w = np.ones(7) # 1d array consisting of 7 ones
print(w.shape)
print(w)

N = np.ones((3, 2)) # 3x2 (3 rows, 2 columns) of ones
print(N.shape)
print(N)

I = np.eye(4) # 4x4 array with ones on the diagonal and zeros elsewhere
print(I.shape)
print(I)

R = np.random.rand(2, 4) # 2x4 array of random values from a uniform distribution
print(R.shape)
print(R)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] (11,)
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5] (8,)
(5,)
[0. 0. 0. 0. 0.]
(2, 5)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(7,)
[1. 1. 1. 1. 1. 1. 1.]
(3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(2, 4)
[[0.99655022 0.00296294 0.47082716 0.01955816]
 [0.1735211  0.23503727 0.76801702 0.11067108]]


In [41]:
# Question 2
print(np.linspace(1, 20, 20)) # 1 to 20, 20 elements
print(np.ones((5, 10)))
print(np.eye((10)))
print(np.random.rand(4, 4))
print(np.arange(0, 101, 5))

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# linspace(start, stop, num) -> controls number of elements
# arange(start, stop, step) -> controls step size



[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[2.73739754e-02 3.60024842e-01 8.09681980e-01 7.60288758e-01]
 [4.95652865e-02 1.18575862e-01 2.00691543e-01 6.03269937e-01]
 [5.66380539e-06 1.35521883e-01 8.18414852e-01 7.12566055e-01]
 [5.32436155e-01 4.52668436e-01 8.50557987e-01 1.68183594e-01]]
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [52]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(M)
# geneeral format: M[row_start:row_end, col_start:col_end]
print("the second row:", M[1])
print("the first row third column first:", M[0, 2])
print("this is subarray of M:\n", M[1:3, 1:3]) # matrix multiplication
print("the first two rows o fM\n", M[0:2, :])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
the second row: [5 6 7 8]
the first row third column first: 3
this is subarray of M:
 [[ 6  7]
 [10 11]]
the first two rows o fM
 [[1 2 3 4]
 [5 6 7 8]]


In [42]:
# question 3
the_matrix = np.array([[21, 31], [35, 45], [10, 20], [90, 100]])
print(the_matrix)
print(the_matrix[])

[[ 21  31]
 [ 35  45]
 [ 10  20]
 [ 90 100]]
